local Queue = require("tests.websocket.shared").Queue

describe("queue", function()
    it("empty", function()
        local q = Queue:new()
        assert.equals(0, #q)
        assert.equals(0, q:size())
    end)
    it("push", function()
        local q = Queue:new()
        q:push_back(0)
        assert.equals(1, q:size())
    end)

    it("pop", function()
        local q = Queue:new()
        q:push_back("a")
        assert.equals(1, q:size())
        q:push_back("b")
        assert.equals(2, q:size())
        assert("a", q:pop_front())
        assert.equals(1, q:size())
        assert("b", q:pop_front())
        assert.equals(0, q:size())
    end)

    it("sync block", function()
        local q = Queue:new()
        vim.defer_fn(function()
            q:push_back("foo")
        end, 1000)
        assert.is_equal(0, q:size())
        assert.is_equal("foo", q:pop_front_sync())
        assert.is_equal(0, q:size())
    end)
end)
